export const WEB3_LOADED = "WEB3_LOADED";
export const WALLET_ADDRESS_LOADED = "WALLET_ADDRESS_LOADED";

//Crowd funding
export const CROWD_FUNDING_CONTRACT_LOADED = "CROWD_FUNDING_CONTRACT_LOADED";

// Project
export const PROJECT_CONTRACTS_LOADED = "PROJECT_CONTRACTS_LOADED";
export const PROJECTS_LOADED = "PROJECTS_LOADED";
export const NEW_PROJECT_CONTRACT_LOADED = "NEW_PROJECT_CONTRACT_LOADED";
export const NEW_PROJECT_LOADED = "NEW_PROJECT_LOADED";